### ISSUE TITLE
FileNotFoundError in bam-to-allc steps

### ISSUE THREAD

**Issue by MichaelPeibo** [lhqing/wmb2023#4]
Hi Hanqing, very helpful package and tutorial. There is an issue that occurred to me when I try to regenerate the results using your provided mamba environment. In the`bam-to-allc` step, it reports an error. I have all dependencies installed as your .yaml file indicates. Any idea on this?
Thanks!

> Building DAG of jobs...
> Using shell: /bin/bash
> Provided cores: 10
> Rules claiming more threads will be scaled down.
> Job counts:
>         count   jobs
>         1       allc
>         1       summary
>         2
> 
> [Thu Jun 22 16:31:40 2023]
> rule allc:
>     input: bam/CEMBA3C_18A3C_R2_P10-1-O5-A2.mC.bam, bam/CEMBA3C_18A3C_R2_P10-1-O5-A2.mC.bam.bai
>     output: allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz, allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz.count.csv
>     jobid: 1
>     wildcards: cell_id=CEMBA3C_18A3C_R2_P10-1-O5-A2
>     threads: 2
>     resources: mem_mb=500
> 
> command bam-to-allc
> bam_path        bam/CEMBA3C_18A3C_R2_P10-1-O5-A2.mC.bam
> reference_fasta /home/peiboxu/wmb2023/mm10/mm10.fa
> output_path     allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz
> cpu     1
> num_upstr_bases 0
> num_downstr_bases       2
> min_mapq        10
> min_base_quality        20
> compress_level  5
> save_count_df   True
> convert_bam_strandness  False
> Traceback (most recent call last):
>   File "/home/peiboxu/micromamba/envs/snm3c/bin/allcools", line 8, in <module>
>     sys.exit(main())
>   File "/home/peiboxu/micromamba/envs/snm3c/lib/python3.7/site-packages/ALLCools/__main__.py", line 834, in main
>     validate_environment()
>   File "/home/peiboxu/micromamba/envs/snm3c/lib/python3.7/site-packages/ALLCools/__main__.py", line 84, in validate_environment
>     check=True,
>   File "/home/peiboxu/micromamba/envs/snm3c/lib/python3.7/subprocess.py", line 488, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/home/peiboxu/micromamba/envs/snm3c/lib/python3.7/subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "/home/peiboxu/micromamba/envs/snm3c/lib/python3.7/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'tabix': 'tabix'
> [Thu Jun 22 16:31:43 2023]
> Error in rule allc:
>     jobid: 1
>     output: allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz, allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz.count.csv
>     shell:
>         /home/peiboxu/micromamba/envs/snm3c/bin/allcools bam-to-allc --bam_path bam/CEMBA3C_18A3C_R2_P10-1-O5-A2.mC.bam --reference_fasta /home/peiboxu/wmb2023/mm10/mm10.fa --output_path allc/CEMBA3C_18A3C_R2_P10-1-O5-A2.allc.tsv.gz --cpu 1 --num_upstr_bases 0 --num_downstr_bases 2 --compress_level 5 --save_count_df
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message

**Comment by MichaelPeibo** [comment]
An update: I executed the code outside of the snakemake pipeline and it worked through the `bam-to-allc` steps.

**Comment by MichaelPeibo** [comment]
An update how to use it in snakemake pipeline: thanks to [this](https://github.com/snakemake/snakemake/issues/352), I added these code under the same rule `allc` to use my micromamba environment for this function:
```
shell:
        'set +eu '
        ' && PS1=dummy'
        ' && . /home/peiboxu/micromamba/etc/profile.d/micromamba.sh '
        ' && micromamba activate {params.conda_env} '
        ' && echo $CONDA_PREFIX; ' 
        ' allcools bam-to-allc '
        ' --bam_path {input.bam} '
        ' --reference_fasta {reference_fasta} '
        ' --output_path {output.allc} '
        ' --cpu 1 '
        ' --num_upstr_bases {num_upstr_bases} '
        ' --num_downstr_bases {num_downstr_bases} '
        ' --compress_level {compress_level} '
        ' --save_count_df'
```
